version: "3"
services:
  db-pg-15-3:
    container_name: postgres-15.3
    image: postgres:15.3
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=auth_db
    ports:
      - "5432:5432"
    restart: on-failure
  auth-manager:
    container_name: app
    build: ./
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "8080:8080"
    restart: always
    links:
      - 'db-pg-15-3:am-database'